-- Public schema tables (aligned with EF migrations/model)

CREATE TABLE users (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username text NOT NULL,
  email text NOT NULL,
  discord_id text NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  last_login_at timestamp with time zone NOT NULL,
  roles text[] NOT NULL,
  avatar_url text NOT NULL,
  youtube text NOT NULL,
  twitch text NOT NULL,
  is_active boolean NOT NULL,
  steam_id text NOT NULL DEFAULT ''::text,
  alt_name text NOT NULL DEFAULT ''::text,
  obs_secret_code text NOT NULL DEFAULT ''::text,
	CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_users_discord_id ON users (discord_id);

CREATE TABLE scorings (
  code text NOT NULL,
  name text NOT NULL,
  scores jsonb NOT NULL,
  modes text[] NOT NULL,
  is_active boolean NOT NULL,
  drop_rate_type text NOT NULL DEFAULT ''::text,
  rates jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT pk_scorings PRIMARY KEY (code)
);

CREATE TABLE seasons (
  code text NOT NULL,
  name text NOT NULL,
  pitch text NOT NULL,
  mode text NOT NULL,
  "desc" text NOT NULL,
  hours real NOT NULL,
  owner_id integer NOT NULL,
  is_active boolean NOT NULL,
  created_at timestamp with time zone NOT NULL,
  created_by text NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  updated_by text NOT NULL,
  admins jsonb,
  schedule jsonb NOT NULL,
  score_items jsonb,
  stats jsonb NOT NULL,
  CONSTRAINT pk_seasons PRIMARY KEY (code),
  CONSTRAINT fk_seasons_users_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_seasons_owner_id ON seasons (owner_id);

CREATE TABLE events (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  start_at timestamp with time zone NOT NULL,
  end_at timestamp with time zone NOT NULL,
  status integer NOT NULL,
  mode text NOT NULL,
  scoring_code text NOT NULL,
  hours real NOT NULL,
  "desc" text NOT NULL,
  seed text NOT NULL,
  prizes jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL,
  created_by text NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  updated_by text NOT NULL,
  is_private boolean NOT NULL DEFAULT false,
  owner_id integer NOT NULL DEFAULT 1,
  private_password text,
  season_code text,
	CONSTRAINT pk_events PRIMARY KEY (id),
  CONSTRAINT fk_events_scorings_scoring_code FOREIGN KEY (scoring_code) REFERENCES scorings (code) ON DELETE CASCADE,
  CONSTRAINT fk_events_users_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_events_seasons_season_code FOREIGN KEY (season_code) REFERENCES seasons (code)
);

CREATE INDEX ix_events_owner_id ON events (owner_id);
CREATE INDEX ix_events_scoring_code ON events (scoring_code);
CREATE INDEX ix_events_season_code ON events (season_code);

CREATE TABLE players (
  event_id integer NOT NULL,
  user_id integer NOT NULL,
  name text NOT NULL,
  avatar_url text NOT NULL,
  stream text NOT NULL,
  status integer NOT NULL,
  score integer NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  logs jsonb,
  CONSTRAINT pk_players PRIMARY KEY (event_id, user_id),
  CONSTRAINT fk_players_events_event_id FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
  CONSTRAINT fk_players_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_players_user_id ON players (user_id);

CREATE TABLE track_logs (
  at timestamp with time zone NOT NULL,
  id text NOT NULL,
  "user" text NOT NULL,
  seed text NOT NULL,
  mode text NOT NULL,
  score integer NOT NULL,
  logs jsonb,
  CONSTRAINT pk_track_logs PRIMARY KEY (at, id)
);

CREATE TABLE runs (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  category text NOT NULL,
  owner_id integer NOT NULL,
  duration_seconds integer NOT NULL,
  created_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL,
  events jsonb,
  record jsonb,
  CONSTRAINT pk_runs PRIMARY KEY (id),
  CONSTRAINT fk_runs_users_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_runs_owner_id ON runs (owner_id);

CREATE TABLE avatars (
  hash text NOT NULL,
  data bytea NOT NULL,
  content_type text NOT NULL,
  uploaded_at timestamp with time zone NOT NULL,
  CONSTRAINT pk_avatars PRIMARY KEY (hash)
);