START TRANSACTION;
DROP TABLE hunts_player;

DROP TABLE hunts;

CREATE TABLE runs (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    category text NOT NULL,
    owner_id integer NOT NULL,
    duration_seconds integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    events jsonb,
    record jsonb NOT NULL,
    CONSTRAINT pk_runs PRIMARY KEY (id),
    CONSTRAINT fk_runs_users_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_seasons_owner_id ON seasons (owner_id);

CREATE INDEX ix_runs_owner_id ON runs (owner_id);

ALTER TABLE seasons ADD CONSTRAINT fk_seasons_users_owner_id FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE;

--INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
--VALUES ('20260219021422_Runs', '9.0.1');

COMMIT;

