
### Setup database
GET {{base_url}}/api/db/migrate

### Seed all data from CSV files
GET {{base_url}}/api/db/seed-all

### Import all the old hunts
GET {{base_url}}/api/import

### Seed a user
POST {{base_url}}/api/db/seed-user
Content-Type: application/json

{
  "username": "oathorse",
  "email": "example@email.com",
  "discordId": "618218180929650698",
  "avatarUrl": "https://cdn.discordapp.com/avatars/618218180929650698/5b6666eb98c57c3c7a3f95e86da809ba.webp?size=240",
  "isActive": true
}

### Seed a user
POST {{base_url}}/api/db/seed-user
Content-Type: application/json

{
  "username": "Henrik",
  "email": "henrik@valheim.help",
  "discordId": "132419724381257738",
  "avatarUrl": "https://cdn.discordapp.com/avatars/132419724381257738/a9a3bbd0e1994e8f8860ddb99967a851.webp?size=240",
  "isActive": true
}

### Seed a user
POST {{base_url}}/api/db/seed-user
Content-Type: application/json

{
  "username": "archy2cold",
  "email": "archy@valheim.help",
  "discordId": "204705568118538240",
  "avatarUrl": "https://cdn.discordapp.com/avatars/204705568118538240/dbe9c963fe521c33b45f93df7b76ee8d.webp?size=240",
  "steamId": "Archy",
  "isActive": true
}

### Seed a user
POST {{base_url}}/api/db/seed-user
Content-Type: application/json

{
  "username": "Warband",
  "email": "warband@valheim.help",
  "discordId": "486516490988814347",
  "avatarUrl": "https://yt3.googleusercontent.com/R3tet0hNJoTpR67vGnO5Avg7XnGUiRfMCETsRbDuvlCSGFRPSCBRHXMzvecwM5W_dvvuvMNXfEE=s160-c-k-c0x00ffffff-no-rj",
  "steamId": "yellow ham grindset",
  "isActive": true
}

### Seed a user
POST {{base_url}}/api/db/seed-user
Content-Type: application/json

{
  "username": "HaWk3y3",
  "email": "hawk3y3@valheim.help",
  "discordId": "392539316854980609",
  "avatarUrl": "https://yt3.googleusercontent.com/8SrhPMKAyXO1QftRokpB_66k8a2FrJqbPGkh-GYyah_4ZSamax9f1zpSc_7sb0Onaw7iprOXKfo=s160-c-k-c0x00ffffff-no-rj",
  "steamId": "Hawk3y3",
  "altName": "ohawk3y3o",
  "isActive": true
}


### Seed scoring
POST {{base_url}}/api/scoring
Content-Type: application/json

{
  "code": "hunt-2024-11",
  "name": "Trophy Hunt 2024 Nov",
  "modes": ["TrophyHunt"],
  "isActive": true,
  "scores": {  
    "PenaltyDeath": -20,
    "PenaltyLogout": -10,
    "TrophyBoar": 10,
    "TrophyDeer": 10,
    "TrophyNeck": 10,
    "TrophyEikthyr": 40,
    "TrophyGreydwarf": 20,
    "TrophyGreydwarfBrute": 20,
    "TrophyGreydwarfShaman": 20,
    "TrophySkeletonPoison": 20,
    "TrophySkeleton": 20,
    "TrophyFrostTroll": 20,
    "TrophySkeletonHildir": 25,
    "TrophyTheElder": 60,
    "TrophyAbomination": 20,
    "TrophyBlob": 20,
    "TrophyDraugr": 20,
    "TrophyDraugrElite": 20,
    "TrophyLeech": 20,
    "TrophySurtling": 20,
    "TrophyWraith": 20,
    "TrophyBonemass": 100,
    "TrophyCultist": 30,
    "TrophyHatchling": 30,
    "TrophyFenring": 30,
    "TrophySGolem": 30,
    "TrophyUlv": 30,
    "TrophyWolf": 30,
    "TrophyCultist_Hildir": 45,
    "TrophyDragonQueen": 100,
    "TrophyDeathsquito": 30,
    "TrophyGoblin": 30,
    "TrophyGoblinBrute": 30,
    "TrophyGoblinShaman": 30,
    "TrophyGrowth": 30,
    "TrophyLox": 30,
    "TrophyGoblinBruteBrosShaman": 65,
    "TrophyGoblinBruteBrosBrute": 65,
    "TrophyGoblinKing": 160,
    "TrophyDvergr": 40,
    "TrophyHare": 40,
    "TrophyGjall": 40,
    "TrophySeeker": 40,
    "TrophySeekerBrute": 40,
    "TrophyTick": 40,
    "TrophySeekerQueen": 1000,
    "TrophyAsksvin": 50,
    "TrophyBonemawSerpent": 50,
    "TrophyFallenValkyrie": 50,
    "TrophyCharredArcher": 50,
    "TrophyMorgen": 50,
    "TrophyVolture": 50,
    "TrophyWarlock": 50,
    "TrophyCharredMelee": 50,
    "TrophyFader": 1000,
    "TrophySerpent": 45,
    "TrophyKvastur": 25
  }
}

### Seed scoring
POST {{base_url}}/api/scoring
Content-Type: application/json

{
  "code": "saga-2024-12",
  "name": "Trophy Saga 2024 Dec",
  "modes": ["TrophySaga"],
  "isActive": true,
  "scores": {  
    "PenaltyDeath": -30,
    "PenaltyLogout": -10,
    "TrophyBoar": 10,
    "TrophyDeer": 10,
    "TrophyNeck": 10,
    "TrophyEikthyr": 40,
    "TrophyGreydwarf": 20,
    "TrophyGreydwarfBrute": 20,
    "TrophyGreydwarfShaman": 20,
    "TrophySkeletonPoison": 20,
    "TrophySkeleton": 20,
    "TrophyFrostTroll": 20,
    "TrophySkeletonHildir": 25,
    "TrophyTheElder": 60,
    "TrophyAbomination": 20,
    "TrophyBlob": 20,
    "TrophyDraugr": 20,
    "TrophyDraugrElite": 20,
    "TrophyLeech": 20,
    "TrophySurtling": 20,
    "TrophyWraith": 20,
    "TrophyBonemass": 100,
    "TrophyCultist": 30,
    "TrophyHatchling": 30,
    "TrophyFenring": 30,
    "TrophySGolem": 30,
    "TrophyUlv": 30,
    "TrophyWolf": 30,
    "TrophyCultist_Hildir": 45,
    "TrophyDragonQueen": 100,
    "TrophyDeathsquito": 30,
    "TrophyGoblin": 30,
    "TrophyGoblinBrute": 30,
    "TrophyGoblinShaman": 30,
    "TrophyGrowth": 30,
    "TrophyLox": 30,
    "TrophyGoblinBruteBrosShaman": 65,
    "TrophyGoblinBruteBrosBrute": 65,
    "TrophyGoblinKing": 160,
    "TrophyDvergr": 40,
    "TrophyHare": 40,
    "TrophyGjall": 40,
    "TrophySeeker": 40,
    "TrophySeekerBrute": 40,
    "TrophyTick": 40,
    "TrophySeekerQueen": 1000,
    "TrophyAsksvin": 50,
    "TrophyBonemawSerpent": 50,
    "TrophyFallenValkyrie": 50,
    "TrophyCharredArcher": 50,
    "TrophyMorgen": 50,
    "TrophyVolture": 50,
    "TrophyWarlock": 50,
    "TrophyCharredMelee": 50,
    "TrophyFader": 1000,
    "TrophySerpent": 45,
    "TrophyKvastur": 25
  }
}


### Seed scoring
POST {{base_url}}/api/scoring
Content-Type: application/json

{
  "code": "rush-2024-11",
  "name": "Trophy Rush 2024 Nov",
  "modes": ["TrophyRush"],
  "isActive": true,
  "scores": {  
    "PenaltyDeath": -10,
    "PenaltyLogout": -5,
    "PenaltySlashDie": -20,
    "TrophyBoar": 10,
    "TrophyDeer": 10,
    "TrophyNeck": 10,
    "TrophyEikthyr": 40,
    "TrophyGreydwarf": 20,
    "TrophyGreydwarfBrute": 20,
    "TrophyGreydwarfShaman": 20,
    "TrophySkeletonPoison": 20,
    "TrophySkeleton": 20,
    "TrophyFrostTroll": 20,
    "TrophySkeletonHildir": 25,
    "TrophyTheElder": 60,
    "TrophyAbomination": 20,
    "TrophyBlob": 20,
    "TrophyDraugr": 20,
    "TrophyDraugrElite": 20,
    "TrophyLeech": 20,
    "TrophySurtling": 20,
    "TrophyWraith": 20,
    "TrophyBonemass": 100,
    "TrophyCultist": 30,
    "TrophyHatchling": 30,
    "TrophyFenring": 30,
    "TrophySGolem": 30,
    "TrophyUlv": 30,
    "TrophyWolf": 30,
    "TrophyCultist_Hildir": 45,
    "TrophyDragonQueen": 100,
    "TrophyDeathsquito": 30,
    "TrophyGoblin": 30,
    "TrophyGoblinBrute": 30,
    "TrophyGoblinShaman": 30,
    "TrophyGrowth": 30,
    "TrophyLox": 30,
    "TrophyGoblinBruteBrosShaman": 65,
    "TrophyGoblinBruteBrosBrute": 65,
    "TrophyGoblinKing": 160,
    "TrophyDvergr": 40,
    "TrophyHare": 40,
    "TrophyGjall": 40,
    "TrophySeeker": 40,
    "TrophySeekerBrute": 40,
    "TrophyTick": 40,
    "TrophySeekerQueen": 1000,
    "TrophyAsksvin": 50,
    "TrophyBonemawSerpent": 50,
    "TrophyFallenValkyrie": 50,
    "TrophyCharredArcher": 50,
    "TrophyMorgen": 50,
    "TrophyVolture": 50,
    "TrophyWarlock": 50,
    "TrophyCharredMelee": 50,
    "TrophyFader": 1000,
    "TrophySerpent": 45,
    "TrophyKvastur": 25
  }
}